### ISSUE TITLE
Walls Insta-Break

### ISSUE THREAD

**Issue by SyndicateServers** [MrTJP/ProjectRed#1573] opened 2020-03-20 02:30 UTC
walls of any kind break with fist instantly

place a wall, punch it

usual block-breaking mechanic

no log

CodeChickenLib-1.12.2-3.2.3.358
ForgeMultipart-1.12.2-2.6.2.83
MrTJPCore-1.12.2-2.1.4.43
ProjectRed-1.12.2-4.9.4.120

![2020-03-19_22 30 08](https://user-images.githubusercontent.com/42458375/77131189-254d8300-6a31-11ea-9192-9ac82084e26d.png)
![2020-03-19_22 30 08_2](https://user-images.githubusercontent.com/42458375/77131191-254d8300-6a31-11ea-8c18-1fa2a80d14f2.png)
![2020-03-19_22 30 07](https://user-images.githubusercontent.com/42458375/77131192-25e61980-6a31-11ea-8ada-05efd5d63101.png)

**Comment by MrTJP** [comment] 2020-04-23 01:41
Confirmed. Will look into it.

**Comment by HunterSpectre** [comment] 2020-10-03 13:41
The problem is still present, walls are destroyed by a hand or a block without an object falling out, but if you hit with a pickaxe, an object falls out.

**Comment by MrTJP** [comment] 2021-04-11 20:22
Fixed on 1.15 branch: 05d7358e645112f8d1239d761f6488584355c81b

**Closed by MrTJP** 2021-04-11 20:22 UTC
Labels: bug
