### ISSUE TITLE
[Bug] Continuing issues with CC: Tweaked compatibility

### ISSUE THREAD

**Issue by devmgardner** [MrTJP/ProjectRed#1835] opened 2024-03-02 18:05 UTC
### Minecraft version

1.16.x

### CodeChickenLib version

4.0.7.445

### CBMultipart version

3.0.4.123

### ProjectRed version

4.15.0

### What happened?

I have an `Advanced Computer` from the `CC: Tweaked` mod, with a `Bundled Cable` directed into the side of it but not ON the computer block itself. I can pass an Analog redstone signal into the computer and read it just fine with `rs.getAnalogInput("left")`, but running `rs.getBundledInput("left")` always returns 0 no matter what.

### Crash log

No crash log.

### How do you make it happen again?

Have tried:
- All 6 sides of the `Advanced Computer` block
- Bundled cables pointed into the block as well as attached to the block directly
- Insulated wires instead of bundled cables

Nothing works with `Bundled Cables` unfortunately.

**Comment by MrTJP** [comment] 2024-05-11 16:09
Duplicate of #1826

**Closed by MrTJP** 2024-05-11 16:09 UTC
Labels: outdated, bug
