### ISSUE TITLE
Routed Interface pipes do not connect to Alchemical Chests from ProjectE

### ISSUE THREAD

**Issue by Kalmeira** [MrTJP/ProjectRed#1305] opened 2018-05-29 21:35 UTC
Routed Interface pipes do not connect to Alchemical Chests from ProjectE. They visibly do not connect and cannot interact with them.

**Comment by MrTJP** [comment] 2018-05-30 00:41
Duplicate of #1278

**Closed by MrTJP** 2018-05-30 00:41 UTC
