### ISSUE TITLE
Crash on specific location (ProjectRed Exploration)

### ISSUE THREAD

**Issue by TeroBlaZe** [MrTJP/ProjectRed#1005] opened 2016-03-05 17:06 UTC
Can someone tell me please what exactly heppened? I stuck on this location.

http://pastebin.com/P61gvjjE

**Comment by bookerthegeek** [comment] 2016-03-05 19:29
First, edit your post and post the log to pastebin and place the link in your edited post.

**Comment by TeroBlaZe** [comment] 2016-03-06 07:21
@bookerthegeek Sorry, my bad. So?

**Comment by TeroBlaZe** [comment] 2016-03-06 12:59
I found several Barrels which caused server to crash using McEdit. After deleting broken tiles I at last was able to join a game. Placement of new Barrels at the same spots didn't caused crash anymore. The reason is still unknown. [Screenshot](http://i.imgur.com/sh0Te2O.png)

**Comment by MrTJP** [comment] 2016-03-07 21:59
The cause is because the barrel had contained a mod item that has since been removed from the game. This will be fixed in the next version.

**Closed** 2016-03-07 22:09 UTC

**Comment by TeroBlaZe** [comment] 2016-03-08 08:20
@MrTJP Thanks. BTW Item NBT Inspector shows no difference between broken and normal barrels. One thing which contained in one of 3 broken barrels was minecraft:log.

As soon as it will be fixed I'll test the issue again later.
