### ISSUE TITLE
1.12.2 Dupe bug

### ISSUE THREAD

**Issue by SFort** [MrTJP/ProjectRed#1473] opened 2019-04-13 20:18 UTC
If you place two block placers pointing at the same block
and activate them at the same time one will copy the inventory of the other.
[Yt vid](https://youtu.be/C-mSj_Xopq0)

**Comment by SFort** [comment] 2019-04-13 20:23
Possibly related to #1466

**Comment by MrTJP** [comment] 2019-06-17 07:25
Duplicate of #1466

**Closed by MrTJP** 2019-06-17 07:25 UTC
