### ISSUE TITLE
Game Crashes on load

### ISSUE THREAD

**Issue by Gryffen1971** [MrTJP/ProjectRed#1456] opened 2019-02-11 01:31 UTC
I tried to load my Mod-Pack with your mod and "The Betweenlands" Mod the game crashes on Load at Step 5 of 7. When i disable "The Betweenlands" or "Project Red" Mods and start loading the game it completes it loading process.

#### Project Red version:

projectred-core 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-Base.jar
projectred-compat 1.0, ProjectRed-1.12.2-4.9.1.92-compat.jar
projectred-integration 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-integration.jar
projectred-transmission 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-integration.jar
projectred-fabrication 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-fabrication.jar
projectred-illumination 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-lighting.jar
projectred-expansion 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-mechanical.jar
projectred-relocation 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-mechanical.jar
projectred-transportation 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-mechanical.jar
projectred-exploration 4.9.1.92, ProjectRed-1.12.2-4.9.1.92-world.jar

#### Forge version:
forge-14.23.5.2811

#### Singleplayer or Multiplayer:
SinglePlayer

#### Installed mods:
Here is the Link:  https://docs.google.com/document/d/1YMN7keX0k9hfq2btK4RCeIAhXb4aSXnV2ORAvF7RUkY/edit?usp=sharing

## Link to full crash log
Here's the Link:  https://docs.google.com/document/d/1dCaqC8zaloN2cE_ZR0ilXZk9Xy7YX4d8Fe76XEWXJzo/edit?usp=sharing

#### How to reproduce:
1. Install "SkyCrane Magic, Mech and Tech Mod Pack
2. Install Project Red (All Mods)
3. Enable all Mods
4. Start Loading Minecraft

#### Expected result:
Game loading Crashes on Step 5 of 7

#### Actual result:
Game crashes on load on Step 5 of 7

I have also posted a report(issue) with the "The Angry Pixel" Team.

**Comment by collwee** [comment] 2019-02-22 01:21
@Gryffen1971 here the latest version of projectred it work with betweenlands https://github.com/MrTJP/ProjectRed/issues/1461

**Comment by Gryffen1971** [comment] 2019-02-22 09:36
What is the latest version of Project Red: Mechanism?

**Comment by MrTJP** [comment] 2019-07-09 22:40
Duplicate of #1429

**Closed by MrTJP** 2019-07-09 22:40 UTC
Labels: bug
