### ISSUE TITLE
Request: Color changing lamp

### ISSUE THREAD

**Issue by Vritra22189** [MrTJP/ProjectRed#1027] opened 2016-04-30 12:03 UTC
it seems there isn't a mod that have a color changing lamp
and the idea is that it have a bundle input, 
then change it's color depending on the active bundle color (assuming only one color is active)
if there is no active color, the lamp is off

i think it might be cool to pair with a Bus Input Panel to change a room's lighting color
or mess with a Bus Randomizer for some disco-like effect

**Comment by MrTJP** [comment] 2016-12-30 16:45
Duplicate of #729. Long time in-the-works project that I will finish up at some point.

**Closed by MrTJP** 2016-12-30 16:45 UTC
