### ISSUE TITLE
Startup Crash With Betweenlands (1.12.2)

### ISSUE THREAD

**Issue by EnderT5** [MrTJP/ProjectRed#1429] opened 2018-11-22 04:12 UTC
Game crashes on startup.
ProjectRed (All of them) Version: 4.9.1.92
Betweenlands Version: 3.4.1
Forge Version: 14.23.5.2775
Crash Report: https://paste.dimdev.org/netajoyudi.mccrash

**Comment by dualinfinities** [comment] 2018-12-28 20:11
downgrading ProjectRed to 4.9.0.086 works with that version, if you prefer an outdated PR to an outdated TBL

**Comment by warplord** [comment] 2019-01-05 14:09
I am getting a similar crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  RandomPatches (randompatches-1.12.2-1.11.0.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.144.jar)
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b161.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.44.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.3-core.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.5.0-build.0236.jar)
  AstralCore (astralsorcery-1.12.2-1.10.10.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (Quark-r1.5-138.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.3.15.0-build.0232.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 1/5/19 4:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Betweenlands (thebetweenlands)
Caused by: java.lang.NullPointerException
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:345)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:325)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147546_a(TileEntityRendererDispatcher.java:81)
	at thebetweenlands.client.render.tile.RenderItemStackAsTileEntity.<init>(RenderItemStackAsTileEntity.java:22)
	at thebetweenlands.client.proxy.ClientProxy.postInit(ClientProxy.java:473)
	at thebetweenlands.common.TheBetweenlands.postInit(TheBetweenlands.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


Any ideas how to fix? I don't want to downgrade PR - can I downgrade betweenalnds?

**Comment by SirTwsted** [comment] 2019-02-26 20:40
I just wanted to point out that Today February 26th 2019th
This crash still happens when using ProjectRed-1.12.2-4.9.1.92  and The Betweenlands v3.4.4
When you actually use a lower version of The Betweenlands such as the one im using now v3.3.13
All works well and no crashes happen.
The crash actually happens when updating The Betweenlands mod to v3.4.4
Just wanted to point this out to everyone and specially the Developers

**Comment by Enekuda** [comment] 2019-03-07 21:52
Same issue, using TheBetweenlands-3.4.6 and ProjectRed-1.12.2-4.9.1.92

Downgrading to TheBetweenlands-3.3.13 works fine!

**Comment by MrTJP** [comment] 2019-07-09 21:13
Can someone confirm if this was fixed by release v4.9.3 from last week?

**Comment by GoryMoon** [comment] 2019-07-10 11:10
Can confirm that this is fixed by v4.9.3

**Closed** 2019-07-10 23:51 UTC
Labels: bug
