### ISSUE TITLE
Crash When Opening Quark Config Screen (NullPointerException in mrtjp.projectred.relocation.MovementManager)

### ISSUE THREAD

**Issue by cjburkey01** [MrTJP/ProjectRed#1349] opened 2018-07-08 04:40 UTC
This problem occurs whenever the config screen for Vazkii's Quark mod is opened and Project Red is installed. Here's the issue on Quark's repo: https://github.com/Vazkii/Quark/issues/896

This happens both when clicking the "Q" button on the main menu and when navigating to the config screen via the "mods" menu button.

And here's my crash report (another can be found at Quark's issue): https://gist.github.com/cjburkey01/2b52442451f03d4d39bd00937e9ba8a5

**Comment by covers1624** [comment] 2018-07-08 05:17
Please for the love of god look at previous issues. Duplicate of https://github.com/MrTJP/ProjectRed/issues/1331

**Comment by cjburkey01** [comment] 2018-07-08 05:18
Oh, whoops, sorry

**Closed by covers1624** 2018-07-08 05:17 UTC
