### ISSUE TITLE
Crash: Registering texture  java.lang.ArrayIndexOutOfBoundsException: 143

### ISSUE THREAD

**Issue by digger5** [MrTJP/ProjectRed#725] opened 2015-02-22 18:36 UTC
Hi, when i try to start my minecraft instance i receive a crash.

Since it's screaming project red I will post it here and let you take a look.

http://pastebin.com/6WD5RC3N

**Comment by 3Pixel** [comment] 2015-02-23 21:37
Same problem here, it is only crashing with projectred activated.

**Comment by unpure** [comment] 2015-02-26 19:57
I got the same crash and its not realy a user error.
The problem seems to be:
B:3Dlogicwires=false

If you set this to true (atleast with build #64 and #65) the game starts fine.
If this is set to false the game will crash with the given error message.

**Comment by warezit** [comment] 2015-02-27 20:06
@digger5 I can confirm I was having this same issue

@unpure I can also confirm changing this value to "true" fixed the problem for me.

Thanks!

**Comment by MrTJP** [comment] 2015-03-02 18:04
Fixed with cc4bbb01c03eab7fedf47a3148816c6926cce702

**Closed by MrTJP** 2015-03-02 18:04 UTC
