### ISSUE TITLE
[Bug] Lamp Halos Disconnected From Lamps

### ISSUE THREAD

**Issue by Waterspark63** [MrTJP/ProjectRed#1871] opened 2024-07-08 23:06 UTC
### Minecraft version

1.20.x

### CodeChickenLib version

CodeChickenLib-1.20.1-4.4.0.512-universal

### CBMultipart version

CBMultipart-1.20.1-3.3.0.146-universal

### ProjectRed version

ProjectRed-1.20.1-4.19.0-beta+3

### What happened?

When you place a inverted/non-inverted lamp, the halo is disconnected from the lamp, and moves around with your cursor.
This is a modpack with oculus & embedium installed (though I do not have any shaders on at the moment, just installed.)
![2024-07-08_16 56 07](https://github.com/MrTJP/ProjectRed/assets/23124229/652b0b72-5653-4b2c-b865-b8d6f2215745)
![2024-07-08_17 01 27](https://github.com/MrTJP/ProjectRed/assets/23124229/88a0ca3a-e796-496e-8e51-c5a2fec49e65)

### Crash log

There is no crash log, or log output when this occurs.

### How do you make it happen again?

Just place the lamp down, and move the cursor around.

**Comment by dkluin** [comment] 2024-07-09 17:43
Can confirm, this also happens with other kinds of lights:
![2024-07-09_19 42 13](https://github.com/MrTJP/ProjectRed/assets/22093800/d5fe53e4-28a8-496d-8d9c-c96c95d8b86e)

**Comment by MrTJP** [comment] 2024-07-11 15:43
Duplicate of #1868. Please refer to that issue.

**Closed by MrTJP** 2024-07-11 15:43 UTC
Labels: bug
