### ISSUE TITLE
Issue / Question - Stock Keeper Chip - Requesting too many items in mutliple-step auto crafting.

### ISSUE THREAD

**Issue by SgtHugoStiglitz** [MrTJP/ProjectRed#1382] opened 2018-08-10 09:11 UTC
I am currently having an issue, that Stock-Keeper chips request too many items, when the items are auto-crafted in several steps.

What I think is happening:

The Items which are being requested are not "in stock" but being crafted in several steps by a set of Automated crafting tables + Crafting chips.

Example for Torches: One Crafting table will process "Blocks of Coal" into "Coal", "Wood" into "Sticks" and finally another crafting table will then process the "Sticks" and "Coal" into "Torches").

It seems like the Stock-Keeper chip is requesting the items it is supposed to hold in Stock several times, before the chip "knows" that the items are on the way. My guess is the chip only stops requesting the items once the "finished product" is "in the pipe and on the way", or when the "final production" in the last crafting table has started.
This means for more complicated items which take several steps to build, or when there is a longer distance between the different steps of the crafting tables, the chip will repeatedly request the item which gets added to the "crafting queue". 

This is not an issue on request-pipes.
Also when the items are "in stock" the Stock-Keeper chip has no issues requesting the right amount.

Maybe somehow let the "chip" "know" that the requested items are being produced, even when it is a multi-step process? (Like on the request pipe) So the chip won't request them again before they are being crafted.
As an alternative, maybe add a "delay" configuration into the stock-Keeper chip, so the Player can define a Request-Delay int he stock keeper chip.

I hope my explanation is clear enough. If not, please let me know. I could provide a video or give you access to our World.

Kind Regards

Michael

Installed Mods:

ChickenChunks-1.12.2-2.4.1.73-universal
CodeChickenLib-1.12.2-3.2.1.350-universal
ForgeMultipart-1.12.2-2.5.0.70-universal
jei_1.12.2-4.11.0.202
MrTJPCore-1.12.2-2.1.3.35-universal
ProjectRed-1.12.2-4.9.1.92-Base
ProjectRed-1.12.2-4.9.1.92-fabrication
ProjectRed-1.12.2-4.9.1.92-integration
ProjectRed-1.12.2-4.9.1.92-lighting
ProjectRed-1.12.2-4.9.1.92-mechanical
ProjectRed-1.12.2-4.9.1.92-world

**Comment by MrTJP** [comment] 2018-10-26 01:30
Duplicate of #1115

**Closed by MrTJP** 2018-10-26 01:30 UTC
