### ISSUE TITLE
Client Crashes upon placing the IC Gate.

### ISSUE THREAD

**Issue by Jonnels** [MrTJP/ProjectRed#1181] opened 2017-06-08 05:21 UTC
Crash Report:

[crash-2017-06-07_23.12.56-server.txt](https://github.com/MrTJP/ProjectRed/files/1059992/crash-2017-06-07_23.12.56-server.txt)

**Comment by MrTJP** [comment] 2017-08-03 12:24
I need more information on this. When/how did this happen? Was it on a server or just single player? Did client only crash or did server as well?

**Comment by erics465** [comment] 2017-08-03 20:17
Happened to me, too. Exactly the same crash report. I'm using the latest 1.10.2 version.
Client crashed in Singleplayer after placing this item: https://projectredwiki.com/wiki/IC_Gate
It seems like the integrated server crashed (and not only the "client"), because the crash report has a "server" in it. If only the client crashed, the crash report would have "client" in it, not "server".

**Comment by MrTJP** [comment] 2017-08-04 20:53
Cant reproduce. The gate works perfectly fine for me in single and multiplayer. What are steps to reproduce on the most recent version? I tried simply placing an IC gate but it functioned correctly. Maybe an image of the blueprint for the IC would help?

**Comment by erics465** [comment] 2017-08-04 22:15
Simply cheat an IC Gate from Creative Mode and place it on the ground. No blueprint needed.
Version: 1.10.2-4.8.4.49
If this isn't reproducable for you, may it have something to do with other mods? Forge Multipart CBE appears in the stacktrace, I'm using version 1.10.2-2.0.0.38.
My Forge version is 12.18.3.2422.

**Comment by BlockyNoob** [comment] 2017-08-08 17:26
Same here. 
crash log:
https://pastebin.com/T1SQA5AB

**Comment by themechman** [comment] 2017-08-26 00:44
Confirmed. Same steps as erics465. Only difference is my Forge is 12.18.3.2281.

Using JEI to import. Only block to crash server. Both smp and ssp.

**Comment by covers1624** [comment] 2017-08-26 07:41
Don't cheat in the ic gate, you build it in the fabricator.

**Comment by themechman** [comment] 2017-08-26 13:24
While that's all lovely, it should be noted in the item data (when you press LSHIFT for example on some mods) that the item should not be creative given. Or add/change the text to red with subtext warning what would happen. That or make it a hidden item somehow. At least try to prevent it.

Thankfully the block does not persist on restart (Not committed to disk) so there is hope of a swift recovery.

**Comment by MrTJP** [comment] 2017-08-26 14:46
You need to fabricate a chip in the IC Printer and then put that chip into a fabricator to actually assemble the gate. The fabricator machine doesn’t yet exist so a temporary recipe is the chip surrounded by 8 circuit plates in a crafting table. As a precaution I will make it not crash when placing an invalid gate.

**Comment by themechman** [comment] 2017-08-27 13:36
Thank you.

**Comment by MrTJP** [comment] 2017-10-16 16:49
As of a3aa13ef06fc43ebadae445b2db7b85b91a652a1, tooltip will tell you of invalid gate and it wont crash if you still choose to place it in-world.

**Closed by MrTJP** 2017-10-16 16:49 UTC
