### ISSUE TITLE
Incompatibility with VoxelMap?

### ISSUE THREAD

**Issue by xJon** [MrTJP/ProjectRed#1518] opened 2019-08-23 04:32 UTC
**Describe the bug**
All clients connected to server are being kicked back to main menu.

**To Reproduce**
1. Install ProjectRed, CodeChickenLib and VoxelMap
2. Have a lamp in your world
3. ???

**Expected behavior**
Not putting players back to main menu unexpectedly.

**Crash Log**
https://pastebin.com/TZ8jLz2N

**Versions**
* CCL Version: 1.12.2-3.2.3.357
* FMP Version: 1.12.2-2.6.2.83
* MrTJPCore Version: 1.12.2-2.1.4.43
* ProjectRed Version: 1.12.2-4.9.4.120
* VoxelMap Version: 1.12.2-1.9.10-Forge

This has been reported to VoxelMap as well.

**Comment by LordMZTE** [comment] 2019-08-31 19:08
seems like a duplicate of #1515

**Comment by MrTJP** [comment] 2021-04-11 21:17
Crashlog is no longer available, and 1.12 support is outdated. Please open another issue if you see this again in 1.15+

**Closed by MrTJP** 2021-04-11 21:17 UTC
Labels: bug

**Comment by xJon** [comment] 2021-04-11 21:26
This crash happened even without ProjectRed, so it was most likely a VoxelMap issue only.
