### ISSUE TITLE
1.10.2 ISSUE:  Comparator not updating

### ISSUE THREAD

**Issue by AnthonyKane5528X** [MrTJP/ProjectRed#1209] opened 2017-06-28 00:49 UTC
Versions with issue: ProjectRed-
* 1.10.2-4.8.2.36
* 1.10.2-4.8.2.41
* 1.10.2-4.8.3.47  
* 1.10.2-4.8.4.49 (Most recent)

Current version (where comparator is working correctly) 
* too far back (sorry but I've gone back 4 (FOUR) versions and it still doesn't work.

Issue:  Redstone Comparator does not update unless broken and replaced or redstone wiring is broken and replaced.  

2nd Issue:  Redstone gates in general do not seem to be updating.  For example the NOT gate did not toggle off when it received a redstone signal.  I had to make a customer NOT gate with Super Circuit maker, which worked fine.

Someone on Reddit said that in 1.10.2 they changed how vanilla redstone works to reduce overhead tick rate lag.  Maybe this has borked the mod.  Anyway, you might want to check this out as I know a lot of people probably prefer Project Red gates over having to make their own with Super Circuit maker (I know I do).

Tested against vanilla comparator that works properly and updates signal strength.

Issue was not fixed in most recent version update.

**Comment by MrTJP** [comment] 2017-10-16 16:51
Duplicate of #1186.

**Closed by MrTJP** 2017-10-16 16:51 UTC
Labels: bug, duplicate
