### ISSUE TITLE
Server Crash, when placing IC Gate

### ISSUE THREAD

**Issue by ChristianLW** [MrTJP/ProjectRed#1031] opened 2016-05-12 15:37 UTC
I was just testing around with the IC stuff, learning how to use it.
But, when I placed down an IC Gate, the internal server crashed (I think).
Error Message: "A fatal error has occured, this connection is terminated".
I can't really give off more information, since I don't know any more about it.
Replicating this shouldn't be hard. Just place down an IC Gate.
I've tested this multiple times. Always the same result.

**Comment by CarsonF** [comment] 2016-05-17 22:32
There's a complete rewrite of IC gates still in progress. I would assume this issue would be addressed with or after that branch is merged.

**Comment by bosto2** [comment] 2016-05-18 07:28
Not enough details but
There has been a issue around for ages and that is if you place down a IC with a running timer it will crash the cliant that placed it down(if this is the case just make ICs that don't have running timers on place (as in have something that triggers the timer after place))

**Comment by ChristianLW** [comment] 2016-05-18 08:31
I made a completely new world with nothing in it.
And I didn't make any type of chip either. Just purely get an IC Gate in hand and place it down.
**Crash**. No timers or anything.

**Comment by ChristianLW** [comment] 2016-05-18 08:36
Also, The IC Workbench and the IC Printer are the same block, but with different meta.
0 = IC Workbench, 1 = IC Printer. So I tried to do a setblock with a meta of 2,
thinking it might place an IC Gate. The result was an invisible block, which drains your FPS,
while looking at it. Destroying it will crash your client (MC crashing too, not just the internal server).

**Comment by bosto2** [comment] 2016-05-18 14:04
Well i can confirm that this does happen, and will probably not see a fix due to these versions of the item not being obtainable in survival(Maybe in the rewrite that CarsonF mentioned)

**Closed** 2017-08-03 12:25 UTC
Labels: outdated

**Comment by ChristianLW** [comment] 2017-08-12 08:12
I did eventually realise the fact, that I need to craft the gate with the IC chip. So I'm quite dumb, but still thanks for the help.
