### ISSUE TITLE
Frame motors crashing client

### ISSUE THREAD

**Issue by Danbot02** [MrTJP/ProjectRed#1521] opened 2019-09-01 02:24 UTC
**Describe the bug**
I have created a double-sided sliding door which will open 2 blocks each way. however when closing, you can only close it halfway, if you attempt to close it completely it has a chance of crashing.

**Expected behavior**
Double-sided-sliding to close fully.

**Crash Log**
https://paste.dimdev.org/ikisupepey.mccrash 

**Versions** CCL Version: 3.2.3.357 Universal
FMP Version: 2.6.1.81 Universal
MrTJPCore Version: 2.1.3.35 Universal
ProjectRed Version: 4.9.1.92 (Base, Compat, Fab, Inter, Lighting, Mech, World)

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/54757785/64070982-1086e900-ccb3-11e9-9af9-1719daab31ec.png)
![image](https://user-images.githubusercontent.com/54757785/64070984-1e3c6e80-ccb3-11e9-92a4-3c887639cd27.png)
If closed by one more it can crash.

Also is this lighting issue normal?
![image](https://user-images.githubusercontent.com/54757785/64070992-44faa500-ccb3-11e9-9031-645ca5cdb507.png)

**Comment by MrTJP** [comment] 2019-09-01 04:24
Duplicate of #1454

**Closed by MrTJP** 2019-09-01 04:24 UTC
Labels: bug
