### ISSUE TITLE
[1.12.2] Chisel Integration [Request]

### ISSUE THREAD

**Issue by acanady** [MrTJP/ProjectRed#1330] opened 2018-06-20 23:38 UTC
Yeah what it says, it'd be cool if there was chisel integration so that Chisel could recognize the basalt and marble from project red

**Comment by MrTJP** [comment] 2018-06-21 23:19
Implemented via 0f2f36b78c839f2daab4e7d2aa2b74f45f1ef6c2. Going to need it tested some more. Not sure if its working yet..

**Comment by MrTJP** [comment] 2018-06-21 23:20
Duplicate of #1136

**Closed by MrTJP** 2018-06-21 23:20 UTC
Labels: implemented in dev
