### ISSUE TITLE
i think im looking at a repeater from project red

### ISSUE THREAD

**Issue by SteelTigerV2** [MrTJP/ProjectRed#1782] opened 2023-06-25 22:07 UTC
**Describe the bug**
integration components not rendering

**To Reproduce**
place any project red integration component in the world

**Expected behavior**
it should render

**Crash Log**
not crashing

*Required for crash.* **DO NOT** paste the entire crash log here. Use pastebin or similar. 

**Versions**
1.18.2
**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.
![2023-06-25_23 41 36](https://github.com/MrTJP/ProjectRed/assets/78177911/e73e9805-5f0b-40e1-aa1d-a03655397038)

**Comment by MrTJP** [comment] 2023-06-25 22:12
I can't reproduce. Can I get a list of your installed mods?

**Comment by Chassx2** [comment] 2023-06-27 05:26
This is related to https://github.com/MrTJP/ProjectRed/issues/1783 and  https://github.com/Asek3/Rubidium/issues/515

**Comment by TheKidThatCodes** [comment] 2023-06-28 16:29
Dupe of #1783?

**Comment by MrTJP** [comment] 2023-09-20 13:54
Fixed by recent commit to Rubidium. See #1783

**Closed by MrTJP** 2023-09-20 13:54 UTC
Labels: bug
