### ISSUE TITLE
Crash with Minecolonies 1.16.5

### ISSUE THREAD

**Issue by Rainemakerx** [MrTJP/ProjectRed#1661] opened 2021-07-25 00:40 UTC
**Describe the bug**
Crash to desktop with Minecolonies installed (circumstances vary but not much)

**To Reproduce**
1. Install minecolonies-0.14.294-BETA-universal, structurize-0.13.200-BETA-universal, project red core, integration, transmission, beta46 all for 1.16.5 forge 36.2.0.
2. Start a colony and select the minimum stock tab on the builder's hut.
3. Experience the crash.
**Expected behavior**
The crash shouldn't be happening, it happens due to an interaction with itemStacks and the two major mod groups

**Crash Log**
https://gist.github.com/Rainemakerx/0533556aa22fa544b030073c30ca1c27
latest log for sanity checking: https://gist.github.com/Rainemakerx/799fb261975faa77a46a47fbf62d2d2f

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: CodeChickenLib-1.16.5-4.0.2.429-universal
* CBMultipart Version: CBMultipart-1.16.5-3.0.2.119-universal
* MrTJPCore Version: N/A
* ProjectRed Version: ProjectRed-1.16.5-4.10.0-beta-46-core

**Screenshots/Videos**
If applicable, add screenshots or video links to help explain your problem.

**Comment by covers1624** [comment] 2021-07-25 00:42
Duplicate of: https://github.com/TheCBProject/CBMultipart/issues/95

**Closed by covers1624** 2021-07-25 00:42 UTC
Labels: bug
