### ISSUE TITLE
Crashing with mekanism installed, also posted the same error on Mekansim Github.

### ISSUE THREAD

**Issue by F34RxPredator** [MrTJP/ProjectRed#1311] opened 2018-06-01 17:32 UTC
The game crashed to launcher when I click on the induction cell in jei to view the recipe and only seems to happen if project red is installed alongside mechanism. Also someone commented on my GitHub post for mechanism that it also crashes with clicking on the creative tab.

The crash report can be found here.

https://pastebin.com/DsWdq6ww

**Comment by MrTJP** [comment] 2018-06-03 20:00
Duplicate of #1304

**Closed by MrTJP** 2018-06-03 20:00 UTC
