### ISSUE TITLE
Crash when holding microblock

### ISSUE THREAD

**Issue by NEXUS2345** [MrTJP/ProjectRed#800] opened 2015-05-31 12:13 UTC
Crash report: http://files.enjin.com/711529/modules/tickets/27383571-1433030165-crash-2015-05-30_18.46.33-client.txt

**Comment by MrTJP** [comment] 2015-05-31 18:13
Duplicate of #797, #796, #795, #787

**Closed by MrTJP** 2015-05-31 18:13 UTC
