### ISSUE TITLE
Crash when putting tools in crafting mediums (any crafting grid/anvil)

### ISSUE THREAD

**Issue by Darkmega18** [MrTJP/ProjectRed#727] opened 2015-02-24 03:27 UTC
Hey there, I'm getting a crash where when I put one of the gem swords (and probably others, since I dare not try them all to make sure or I'll be here for an hour) into a crafting bench. A similar crash is happening with mekanism here: [https://github.com/aidancbrady/Mekanism/issues/2151] and here: [https://github.com/aidancbrady/Mekanism/issues/1913]

Heres the crash that I got with the sword in crafting bench: http://pastebin.com/xGmpSstz

**Comment by simon816** [comment] 2015-02-24 10:39
Duplicate of #667
Looks like something wrong with Botania

**Comment by Darkmega18** [comment] 2015-02-24 13:48
and Vazkii points finger at mine and blade. and then mine and blade points finger back at mekanism who after not having seen someone post the error in a while says to ask vazkii who immediately closes issue and points it back to an older mekanism issue which I pointed to this after getting data on which other mods have this problem which results in this issue. So who has problem? :V...

**Comment by CubeWrench202** [comment] 2015-02-25 04:33
So mekanism breaks mine and blade, mine and blade breaks botania, and botania breaks ProjectRed?Sounds like a drama generator :P

**Comment by Darkmega18** [comment] 2015-02-25 09:23
in otherwords it's one of those "I dunno, mine looks fine, he probably done it, but I dunno" sorta bugs where it's just annoying. :V but lol, drama generator.

**Comment by MrTJP** [comment] 2015-03-02 17:33
Perhaps bbb24bb3ec77bfecee4ce4754d0354e633d3d538 will fix this.

**Closed by MrTJP** 2015-03-02 17:33 UTC
