### ISSUE TITLE
1.12.2 Some chunks did not load microblocks

### ISSUE THREAD

**Issue by matix931** [MrTJP/ProjectRed#1292] opened 2018-05-19 08:00 UTC
After some time for example playing at night then connecting at morning, some chunks are missing microblocks. 
Server restart helps, reconnecting did not help, blocks are just missing, there is no collison.
No error logs, only some warrning probably not related to this problem.

LOG: https://pastebin.com/CnYFgEVF

Problem exists on:
```
Forge: 1.12.2-14.23.3.2655
FMP: 1.12.2-2.4.1.57
PR version: 4.8.6.66
```
AND
```
Forge: 1.12.2-14.23.3.2698
FMP: 1.12.2-2.4.2.58
PR version: 4.8.6.74
```

Update: It is happening on chunk loading/unloading.
If you go far away from placed microblocks and then return to this place, some chunks are fixed and some are missing microblocks.

**Comment by matix931** [comment] 2018-05-19 11:04
Update: It is happening on chunk loading/unloading.
If you go far away from placed microblocks and then return to this place, some chunks are fixed and some are missing microblocks.

**Comment by covers1624** [comment] 2018-05-21 20:57
Duplicate of https://github.com/MrTJP/ProjectRed/issues/1277

**Closed by covers1624** 2018-05-21 20:57 UTC
