### ISSUE TITLE
[Feature Request] Bundled cable cells

### ISSUE THREAD

**Issue by Whodundid** [MrTJP/ProjectRed#1046] opened 2016-07-04 05:23 UTC
Here's a concept idea for some gate cells that could be really useful, especially in ICs. I hope you might consider adding these at some point down the road.

Their function would be the same of how a normal null cell would work, just now incorporating bundled cables instead of the red alloy wire.

![bundled alloy cell concept](https://cloud.githubusercontent.com/assets/16334910/16551367/1935197c-4175-11e6-8bc4-627f48cd5508.png)
![bundled cell](https://cloud.githubusercontent.com/assets/16334910/16551369/1d89dfee-4175-11e6-92cc-71a14c2beb68.png)

**Comment by Sasszem** [comment] 2016-07-05 21:34
Would be awesome.

**Comment by evg-zhabotinsky** [comment] 2017-01-01 12:32
Duplicate of #843, more or less.
And if IC backend reimplementation is still planned, not going to see these earlier.

**Comment by MrTJP** [comment] 2019-06-18 10:12
Duplicate of #843

**Closed by MrTJP** 2019-06-18 10:12 UTC
Labels: enhancement, under consideration
