### ISSUE TITLE
Spong issue?

### ISSUE THREAD

**Issue by codydbgt** [MrTJP/ProjectRed#1368] opened 2018-07-22 21:45 UTC
i can make them over and over i made a simple system with pipes and any time i go some where and then go back to reload the chunk it removes all the pipes with this error ... 

`read/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$1{tileType=null, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=23469, y=88, z=-26419}, blockMetadata=-1} - class class TileMultipart_cmp$$1
[21:38:48] [Server thread/ERROR] [Sponge]: TileEntity is not registered TileMultipart_cmp$$2{tileType=null, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=23470, y=88, z=-26418}, blockMetadata=-1} - class class TileMultipart_cmp$$2`

**Comment by codydbgt** [comment] 2018-07-22 21:46
i will remove sponge to do further testing later in the day

**Comment by covers1624** [comment] 2018-07-22 22:08
Duplicate of https://github.com/TheCBProject/ForgeMultipart/issues/33

**Closed by covers1624** 2018-07-22 22:08 UTC
