### ISSUE TITLE
[1.12.2] Large Integrated Circuits crash and corrupt the world when placed down

### ISSUE THREAD

**Issue by anthonyheddings** [MrTJP/ProjectRed#1316] opened 2018-06-09 20:48 UTC
Building an 8 bit full adder in PR Fabrication:

![6492504c-8f82-4558-88a6-b300f846932c](https://user-images.githubusercontent.com/16063122/41195952-aa8d3510-6c04-11e8-9045-9c3a1cee7ef1.jpg)

This crashes the game whenever placed. Built a 48x48 variant, still crashes. I built an 8 bit ANDer (much less gates) and it doesn't crash, though the game lags for a second when placing it down.

Crash log:
`[16:14:53] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 7529ms behind, skipping 150 tick(s)
[16:14:53] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at tonius.simplyjetpacks.item.Jetpack.loadConfig(Jetpack.java:305) ~[Jetpack.class:?]
	at tonius.simplyjetpacks.item.Jetpack.loadAllConfigs(Jetpack.java:230) ~[Jetpack.class:?]
	at tonius.simplyjetpacks.network.message.MessageConfigSync.handleMessage(MessageConfigSync.java:51) ~[MessageConfigSync.class:?]
	at tonius.simplyjetpacks.network.message.MessageConfigSync$1.run(MessageConfigSync.java:42) ~[MessageConfigSync$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[16:14:53] [main/INFO] [Actually Additions]: Receiving (new or changed) Player Data for player jlunsford.
[16:14:53] [main/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 48 advancements
[16:14:54] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[16:14:54] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[16:14:54] [main/INFO] [journeymap]: Loading journeymap.topo.config
[16:14:54] [main/INFO] [journeymap]: Loaded 3 waypoints from /Users/anthonyheddings/ftb/FTBContinuum/minecraft/journeymap/data/sp/The Brain/waypoints
[16:14:54] [main/INFO] [journeymap]: Mapping started in /Users/anthonyheddings/ftb/FTBContinuum/minecraft/journeymap/data/sp/The Brain/DIM0. Memory: 3703MB total, 1795MB free 
[16:14:54] [JM-task-6/WARN] [journeymap]: java.lang.NullPointerException

[16:15:41] [Netty Local Client IO #4/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:534) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[16:15:41] [Netty Local Client IO #4/INFO] [SimplyJetpacks]: Loading configuration files
[16:15:41] [main/INFO] [journeymap]: Mapping halted in /Users/anthonyheddings/ftb/FTBContinuum/minecraft/journeymap/data/sp/The Brain/DIM0
`

**Comment by MrTJP** [comment] 2018-06-12 20:18
Hmmm.  Seems to happen when packets get very large. I thought CCL’s PacketCustom was suppose to handle splitting up large packets?

**Comment by covers1624** [comment] 2018-06-12 20:28
I think it should? Ill check tomorrow and poke CB to see if that was intended, it /should/ be simple to do anyway.

**Comment by anthonyheddings** [comment] 2018-06-12 20:29
Yeah it seems to not just be me either, https://github.com/MrTJP/ProjectRed/issues/1257

**Comment by MrTJP** [comment] 2018-06-13 16:03
Duplicate of #1257

**Closed by MrTJP** 2018-06-13 16:03 UTC
Labels: bug
