### ISSUE TITLE
Item transport pipes keep disappearing

### ISSUE THREAD

**Issue by starrman14** [MrTJP/ProjectRed#1293] opened 2018-05-21 20:14 UTC
Just as the title suggests, I created an item sorting system using the item transport pipes and it will disappear  after a couple hours of play. This has happened twice so far, nothing else on the server is disappearing. What should I do, thank you for your help.

**Comment by covers1624** [comment] 2018-05-21 20:57
Duplicate of https://github.com/MrTJP/ProjectRed/issues/1277

**Closed by covers1624** 2018-05-21 20:57 UTC
