### ISSUE TITLE
[Bug] Non full blocks are duplicated when using FTBUltimine

### ISSUE THREAD

**Issue by Blackalf14** [MrTJP/ProjectRed#1900] opened 2024-11-17 19:03 UTC
### Minecraft version

1.20.x

### CodeChickenLib version

4.4.0.516

### CBMultipart version

3.3.0.146

### ProjectRed version

4.20.0-beta+5

### What happened?

Adds more info to #1837

Any ProjectRed (Illumination, Integration and Transmission addons included) non full blocks are duplicated upon using FTBUltimine.

To be more exact any block outside of the one you're actually mining is duplicated meaning that if you're mining 3 Red Alloy Wire (for example) you'll get 5 (3*2-1). The duplicated blocks also appear when doing so in creative (meaning you'll get 2 Red Alloy Wire).

Note: Every blocks affected by that issue are all considered as a same block by FTBUltimine (shown in the screenshot below)

At first I thought this issue was only happening to blocks that drop themselves when the block they're sitting on is broken but turns out the issue also happens to Framed Insulated Wires, Framed Bundle Cables and Framed Low Load Power Line which are not prompt to that.

Turns out the only blocks where the issue does not happen are the Illumar Lamps, Electrotine Generator ect... which are all full blocks.

Further more this issue does not happen to redstone or blocks from other mods that drop themselves when the block they're standing on is broken.

Here's a screenshot of a list of blocks, the ones inside the FTBUltimine activation zone are affected by the issue, the others are not:
![image](https://github.com/user-attachments/assets/84db929c-9583-4771-ac8b-4926beb828f2)

If anything ends up as non clear, please tell me!

### Crash log

No crashes

### How do you make it happen again?

Add the shown above CCL, CCM and ProjectRed mod versions.
Add FTBUltimine 2001.1.5 (currently latest).
Put multiple non full blocks from ProjectRed close to each other.
Ultimine them.
Dupe should happen whether you are in survival or creative.

**Comment by MrTJP** [comment] 2024-11-17 20:27
Thanks for the additional info. This is probably caused by how Multipart blocks handle harvesting.

**Comment by MrTJP** [comment] 2024-11-17 20:28
Closing as duplicate #1837. We will track this issue there.

**Closed by MrTJP** 2024-11-17 20:28 UTC
Labels: bug
