### ISSUE TITLE
Crash with Minecolonies

### ISSUE THREAD

**Issue by DcNdrew** [MrTJP/ProjectRed#1299] opened 2018-05-22 19:48 UTC
Hi!

I had no problems for some hours, but today I wanted to start my singleplayer world, and my save crashed. I sent the log to the Minecolonies team, but they said it's not on their side.

Here is the crash: 
https://paste.ee/p/OoU2c (since I updated to PR version .74 instead of .66, same crash)
And the issue I posted:
https://github.com/Minecolonies/minecolonies/issues/2469

Thank you! :)

**Comment by arkman575** [comment] 2018-05-31 09:45
Same as above. Updated to .94, and same result. Quick feedback would be appreciated.

**Comment by XenoIntegrate5** [comment] 2018-06-01 16:23
I appreciate you referencing this mod author, but could you give some response on the state of this issue being fixed? This is something game breaking for many, especially those of us that love both mods. A simple "It's being fixed as we speak" would suffice.

**Comment by MrTJP** [comment] 2018-06-01 17:03
I honestly have no idea why this is happening. The block states are being set up the same as every other block in the mod so I don’t know why this specific block is causing this crash.

**Comment by XenoIntegrate5** [comment] 2018-06-02 06:07
Got it, I'm sorry for all of this confusion :( 

Hopefully, a solution arises sooner or later, best of luck :D

**Comment by covers1624** [comment] 2018-06-02 07:09
I've seen this before, strings that are the same not matching properly, the solution was to use String.intern() everywhere.

**Comment by DrEthan77** [comment] 2018-06-02 21:44
would be nice if this was fixed :D

**Comment by arkman575** [comment] 2018-06-17 08:41
Was this issue fixed in the new release?

**Comment by arkman575** [comment] 2018-06-17 09:03
As of the most recent iteration, the bug is still present. I will supply the latest log for your study. 

[crash-2018-06-17_02.01.09-server.txt](https://github.com/MrTJP/ProjectRed/files/2108813/crash-2018-06-17_02.01.09-server.txt)

**Comment by covers1624** [comment] 2018-06-18 11:53
I was able to reproduce this with an experimental mod of mine, i have a local fix in CCL for this crash, its bundled in with a bunch of other in progress stuff im still testing before i push.

**Comment by DrEthan77** [comment] 2018-06-18 13:11
yay! fixed stuff!

**Comment by arkman575** [comment] 2018-06-23 10:08
Brillaint! I just lost a hardcore world, so when this mod updates, I’ll slap it in my pack and start a whole new one just in time!

**Comment by DrEthan77** [comment] 2018-06-30 18:44
so covers1624 is there any reason why you haven't committed it yet?

**Comment by covers1624** [comment] 2018-07-01 00:11
The commit was to CCL 3.2, the issue is staying open here as project red hasn't bumped to require that version yet.

**Comment by arkman575** [comment] 2018-07-01 08:35
If I install the new CCL, will it fix the bug?

**Comment by arkman575** [comment] 2018-07-09 08:01
where do you have a release of the new CCL?

**Comment by skellitor301** [comment] 2018-08-19 12:39
Is there a fix for the 1.10 version?

**Comment by covers1624** [comment] 2018-08-19 17:48
No, 1.10 is unsupported.

**Closed** 2019-06-17 12:22 UTC
Labels: fixed
