### ISSUE TITLE
Crash in getWorldStructs

### ISSUE THREAD

**Issue by LemADEC** [MrTJP/ProjectRed#1437] opened 2018-12-09 00:56 UTC
As of 4.9.1.92, an intermittent crash is observed upon disconnecting from a server.

```
java.lang.NullPointerException: Batching chunks
	at mrtjp.projectred.relocation.MovementManager$.getWorldStructs(movement.scala:38)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:345)
	at mrtjp.projectred.relocation.WrappedTileMap.get(renders.scala:325)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147546_a(TileEntityRendererDispatcher.java:81)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147547_b(TileEntityRendererDispatcher.java:95)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:171)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Unknown Source)
```

https://gist.github.com/LemADEC/cb41771a5d56503beb0877be5c685241

**Comment by MrTJP** [comment] 2019-07-09 21:12
Duplicate of #1429

**Closed by MrTJP** 2019-07-09 21:12 UTC
Labels: bug
