### ISSUE TITLE
(Bug) Stock keeper chip keeps requesting too many items

### ISSUE THREAD

**Issue by Greg9711** [MrTJP/ProjectRed#1417] opened 2018-10-24 15:16 UTC
The Stock Keeper Chip keeps requesting the items even if they are in the middle of beeing crafted, this issue ( #1382 ) states the same problem and explains it better. I´m just creating another issue because the other one didn´t get any replies or comments and might be overlooked. I hope this gets fixed. Thanks for your time.

**Comment by MrTJP** [comment] 2018-10-26 01:30
Duplicate of #1115

**Closed by MrTJP** 2018-10-26 01:30 UTC
