### ISSUE TITLE
Crash with Betweenlands mod. 

### ISSUE THREAD

**Issue by warplord** [MrTJP/ProjectRed#1442] opened 2019-01-05 14:19 UTC
https://pastebin.com/DQxuX4Dm

Crash on startup. Any ideas what to do?

**Comment by Denoknight** [comment] 2019-01-05 15:50
Same problem. I'm gonna test with Betweenlands versions.

**Comment by GoryMoon** [comment] 2019-01-14 02:13
Duplicated of #1429 
`downgrading ProjectRed to 4.9.0.086 works with that version, if you prefer an outdated PR to an outdated TBL` or not using the `Project Red - Mechanical` part works.
This has been fixed since mid July 2018 but not released yet.

**Comment by warplord** [comment] 2019-01-18 22:32
Can we get a release with maybe other fixes if there are any, please?

**Comment by DemonfangArun** [comment] 2019-02-03 00:14
"Me Too": https://paste.dimdev.org/qadovopame.mccrash
Why has there not been an update to fix this yet? It also appears there have been no updates since last june, is this mod dead?

**Comment by collwee** [comment] 2019-02-22 01:17
https://github.com/MrTJP/ProjectRed/issues/1461

**Comment by MrTJP** [comment] 2019-07-09 20:58
Can someone confirm if this issue is solved with release v4.9.3 from last week?

**Comment by MrTJP** [comment] 2019-07-09 21:09
Duplicate of #1437

This issue will be tracked there.

**Closed by MrTJP** 2019-07-09 21:09 UTC
Labels: bug

**Comment by MrTJP** [comment] 2019-07-09 21:11
Duplicate of #1429
