### ISSUE TITLE
Battery Box in/out broken.

### ISSUE THREAD

**Issue by NicoNekoDev** [MrTJP/ProjectRed#1523] opened 2019-09-09 10:44 UTC
**Describe the bug**
The Battery Box has only one face for input/output for charging batteries

**To Reproduce**
1. Place a battery box, make sure it have power inside
2. Put empty batteries inside a chest (or a storage)
3. Put tubes directly to battery box and start sending empty batteries from the chest
-> first thing: input for charging batteries is above the battery box, it doesn't work other way
4. Now that batteries are charged, try outputing them
-> second thing: out for charged batteries is above the battery box, it doesnt work other way

**Expected behavior**
The charged batteries to be outputed from other side, not the one that I currenlty input.
There's no tube/block/etc that I know that have the input and output functions at the same time.

**Crash Log**
None, everything good here :)

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CCL Version: 1.12.2-3.2.3.357-universal
* FMP Version: 1.12.2 - 14.23.5.2838
* MrTJPCore Version: 1.12.2-2.1.4.43-universal
* ProjectRed Version: 1.12.2-4.9.4.120

**Screenshots/Videos**
Here's my setup.
https://imgur.com/a/yK3CZF5

**Comment by nicuch** [comment] 2019-09-09 14:24
Well, I found out that the Charging Bench  exists, so now I can automate my battery charging station. If this is not a bug, close the issue, thanks.

**Comment by MrTJP** [comment] 2021-04-12 06:22
Currently, the battery box's top slot it linked to the top side of the block, and all other sides access the bottom slot.

**Closed by MrTJP** 2021-04-12 06:22 UTC
Labels: bug

**Comment by NicoNekoDev** [comment] 2021-04-12 08:55
Nice, thanks for replying after 2 years.
