### ISSUE TITLE
[1.18.2] Conflict with JourneyMap Waypoints

### ISSUE THREAD

**Issue by jyrukii** [MrTJP/ProjectRed#1799] opened 2023-08-18 01:25 UTC
**Describe the bug**
The conflict between these mods is causing JourneyMap's waypoints to visually not show up at the correct locations in the world. Sending the issue to JourneyMap as well.

**To Reproduce**
1. Open a new world
2. Use JourneyMap to create a waypoint (Default key 'J', then navigate down to "Waypoints")
3. Create a waypoint

**Expected behavior**
Beacons for waypoints to align with the actual waypoint. Sending the issue to JourneyMap as well.

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed.
* CodeChickenLib-1.18.2-4.1.4.488
* CBMultipart-1.18.2-3.1.0.137
* ProjectRed-1.18.2-4.16.0-beta-17-core
* journeymap-1.18.2-5.9.7

**Screenshots/Videos**
Waypoint is where I'm currently standing, but the game renders the waypoint at approx. half of the waypoints value, i.e. if the waypoint is supposed to be at (100, 50, 200), it will actually render at (50, 25, 100).

![image](https://github.com/MrTJP/ProjectRed/assets/109630588/e6625172-3835-4109-a25c-d838f425fe9e)

**Comment by MrTJP** [comment] 2023-11-18 22:43
Are you running in Fabulous graphics mode?

**Comment by VirtualGaming1** [comment] 2023-11-18 22:55
I am getting the same issue as well

> Are you running in Fabulous graphics mode?

what is Fabulous graphic mode?

**Comment by MrTJP** [comment] 2023-11-18 22:58
It's the new transparency shader based rendering mode. ProjectRed has lighting shaders now that are active when that mode is used, so was just wondering if this was caused by it:

https://github.com/MrTJP/ProjectRed/discussions/1775

**Comment by VirtualGaming1** [comment] 2023-11-18 23:29
if it was enabled by default. I had not change any setting. the way point dose move when you move as well. that is the strange part

**Comment by MrTJP** [comment] 2023-11-29 22:01
Confirmed. And just as with issue #1807, issue is only present in legacy Fast/Fancy modes. Fixed by baaeb00b2dc06d6ac47aa45f66158509b8cd80e9

**Closed as completed** 2023-11-30 02:07 UTC
Labels: bug
