### ISSUE TITLE
CC:Tweaked compatibility

### ISSUE THREAD

**Issue by sereyn** [MrTJP/ProjectRed#1670] opened 2021-08-26 15:40 UTC
**Describe the bug**
Project red bundled cables don't connect to CC:Tweaked computers. Even `rs.setBundledOutput("right", colors.white)` doesn't work for instance (yes I connected a white cable to test that).

**To Reproduce**
![cc](https://user-images.githubusercontent.com/33748126/130992968-82f1f2ff-9ffd-42fe-828c-5ddd2f9ad581.png)

**Expected behavior**
The cable should be connected to the computer.

**Versions**
Java 11
![cc2](https://user-images.githubusercontent.com/33748126/130993316-2f4b8689-e9d2-453e-8453-83d0ddf78a73.png)

**Comment by devmasu** [comment] 2021-08-28 17:10
I have the same issue. Insulated cables can connect, but not the bundle one.

**Comment by MrTJP** [comment] 2021-09-13 03:22
Duplicate of #1630

**Closed by MrTJP** 2021-09-13 03:22 UTC
Labels: bug
