### ISSUE TITLE
(1.18.2) Game Freeze If Output Of Bus Converter Is Connected To Redstone Input Of Bus Input Panel And Is Powered

### ISSUE THREAD

**Issue by nohax955** [MrTJP/ProjectRed#1809] opened 2023-11-17 16:45 UTC
**Describe the bug**
Game Freeze If Output Of Bus Converter Is Connected To Redstone Input Of Bus Input Panel And Is Powered

**To Reproduce**
1. Place input bus panel
2. Place bus converter with output pointing towards redstone input of bus input panel
3. Power bus converter

**Expected behavior**
Game Freeze and you cant really do much

**Versions**
Include versions of the dependencies. And since you're looking at it, make sure ProjectRed is up to date. Don't submit bugs for old versions, as they could have been fixed. 
* Minecraft Version: 1.18.2
* CCL Version: latest
* FMP Version: latest
* MrTJPCore Version: latest
* ProjectRed Version: latest

**Comment by MrTJP** [comment] 2023-11-21 18:46
Addressed in 9180cd9a5d65383be5278a086733509d29fd1bf9. Caused by an infinite loop server-side. Didn't have anything to do with the input panel gate though. Was able to repro with just the converter gate alone

**Closed** 2023-11-21 19:02 UTC
Labels: bug
