### ISSUE TITLE
Block Update Causes Crash

### ISSUE THREAD

**Issue by CADProgramming** [MrTJP/ProjectRed#1489] opened 2019-07-03 13:06 UTC
When a sticky piston, (probably regular piston also), collides with the powered redstone cable, instead of reacting like regular redstone and popping it off the block, Minecraft instead crashes. The log file is attached
[latest.log](https://github.com/MrTJP/ProjectRed/files/3355067/latest.log)

**Comment by MrTJP** [comment] 2019-07-11 21:46
Do you mean if the piston pushes the block that the wire is sitting on or if it pushes the actual wire? Please provide more details on the actual setup.

**Comment by MrTJP** [comment] 2019-07-14 20:24
Closing this. I cannot reproduce and the log shows no mention at all of Project Red. Looks like a crash related to JEI/NEI.

**Closed by MrTJP** 2019-07-14 20:24 UTC
Labels: bug
