### ISSUE TITLE
Crash when using the Project Bench

### ISSUE THREAD

**Issue by paul-soporan** [MrTJP/ProjectRed#1395] opened 2018-09-10 17:45 UTC
Hi! So I was playing a modified version of the Direwolf20 1.12 pack(that included Project Red) and I experienced a crash when I was inside the Project Bench and tried to form a recipe of a Basic Coil from Actually Additions. I right clicked the RCs(Restonia Crystals) like this:
| Slot 1 | RC(1) | Slot 3 |              
| RC(2) | Slot 5 | RC(3) |
| Slot 7 | RC(4) | Slot 9 |
And when placing the bottom one(RC 4), the game crashed: 
[crash-2018-09-10_19.52.20-client.txt](https://github.com/MrTJP/ProjectRed/files/2367766/crash-2018-09-10_19.52.20-client.txt)
When I reentered the world I noticed that the fouth RC just dissappeared. It wasn't in the Project Table, neither in my inventory, neither on the ground. If you have time, could you look into this, please? I am sorry if this isn't caused by your mod.
And thank you a lot for porting it to 1.12!
Have a nice day!

**Comment by MrTJP** [comment] 2018-10-26 05:29
Could you try and find more instances where this crash happens? I can't find any reason for this to occur. Possibly could be a bad recipe.

**Comment by MrTJP** [comment] 2019-06-23 14:45
Closing because of no additional information and unable to reproduce.

**Closed by MrTJP** 2019-06-23 14:45 UTC
