### ISSUE TITLE
payload may not be larger than 32767 bytes. - Integration in (1.10.2)

### ISSUE THREAD

**Issue by Nebuchadnectar** [MrTJP/ProjectRed#1257] opened 2018-04-26 03:55 UTC
I have found lots of post, from many a mod about this error. So I think it might be something else reacting to your mod.
  I was playing around in a single player world, I made a few simple IC gates, I thought 'gee, this is amazing'. When I made my first serious IC gate and place it, instant crash, with that dreaded packet error. I can't return to the map undo this.  
  If there is a limit to what the ICs can hold, perhaps a 'piece limit' on them would help sort this for others. But I rather hope you folks have a fix, tbh. I was only trying to make a driver for your 7 segment display. I didn't think it was that big a circuit. But seeing that the simple IC gates didn't suffer from this makes me think it may be a size issue. Here it is. ... I didn't think '2x7seg' was a killing word.

![akillingword](https://user-images.githubusercontent.com/38743828/39284936-c9cd5fc0-48e3-11e8-885d-2c19c85236bc.png)

Thank you in advance for any help.

**Comment by MrTJP** [comment] 2018-05-08 23:27
Where is the crash log?

**Comment by covers1624** [comment] 2018-06-18 11:56
This must be related to NBT on the ItemStack. There isn't much we can do about it, but i have some thoughts i need to ponder over for a bit.

**Comment by kitlith** [comment] 2018-08-05 00:35
Has this been fixed already without closing this issue?

![8bit_dualreadx4ic](https://user-images.githubusercontent.com/7027737/43681565-bfb11e56-980b-11e8-911d-c577e5c6fb63.png)

This IC that I created yesterday appears to be larger than the one in #1316 (closed as duplicate of this) but my game does not crash when placing it. It stops/lags for a few seconds, but then it works fine.

**Comment by MrTJP** [comment] 2019-06-18 09:30
@covers1624, can you look over this one last time before we close this out? My understanding is that PacketCustom handles splitting large packets.

**Comment by MrTJP** [comment] 2021-04-11 22:43
No longer relevant. Fabrication is receiving a major rewrite in the 1.15 port

**Closed by MrTJP** 2021-04-11 22:43 UTC
Labels: bug
