### ISSUE TITLE
Logic gates icon and items held on hand flickering

### ISSUE THREAD

**Issue by daniel-pg** [MrTJP/ProjectRed#1557] opened 2020-01-26 00:31 UTC
**Describe the bug**
 When switching too many logic gates in chain, both Logic gates items held on hand and icons will start to flicker for some reason. What's even more interesting is the fact that this works even with different types of logic gates. E.g.: switching lots of OR gates in chain may cause flickering on AND gates icons on the hotbar. Also, logic gates placed on the ground also appears to be affected by this bug.

**To Reproduce**

1. Place some OR gates in chain, one after the another.
2. Put a lever next to the input of the first gate on the chain.
3. Switch the lever on/off a few times.
4. You should see the redstone torches inside the logic gates flickering unexpectedly.
NOTE: for some reason this doesn't always happen, so you need to be very patient to reproduce this bug.

**Expected behavior**
1. Icons on the hotbar, items held on hand or placed on the ground should not flicker due to switching circuits.

**Versions**
* Minecraft: 1.12.2
* CCL Version: 3.2.3.358
* FMP Version: 2.6.2.83
* MrTJPCore Version: 2.1.4.43
* ProjectRed Version: 4.9.4.120 : Base, compat, fabrication, integration, lighting, mechanical

**Screenshots/Videos**
I was able to capture the exact moment when the gate flickered.
![2020-01-25_20 25 12](https://user-images.githubusercontent.com/38893804/73129048-3dfd6780-3fb1-11ea-858b-c289d4edfb47.png)

**Comment by daniel-pg** [comment] 2020-01-30 01:42
Oops! After further research, i think this is the same issue as #1536, although the author doesn't mention the fact that this bug also affects the icons on the hotbar.

**Comment by TheDarkDnKTv** [comment] 2020-09-07 10:49
Unfortunately, i wasnt able to build ALU module on my processor on 1.12.2 because logic gates is really buggy, i thougth it is only visual glithc  theay are flickering many times, buth unfortunately it is not only visual. When switching many gates in the row they are spamming some time random redstone output.

**Comment by daniel-pg** [comment] 2020-09-23 20:09
> Unfortunately, i wasnt able to build ALU module on my processor on 1.12.2 because logic gates is really buggy, i thougth it is only visual glithc theay are flickering many times, buth unfortunately it is not only visual. When switching many gates in the row they are spamming some time random redstone output.

I wasn't able to replicate such behavior, so i can't assert that the problem you described is related to this visual glitch. How did you arrange your circuit? Did you use Integrated Circuits?

**Comment by TheDarkDnKTv** [comment] 2020-09-23 21:18
I was building from dedicated logic modules, may be will get a video about it later.

**Comment by MrTJP** [comment] 2021-07-05 19:50
Was finally able to reproduce this, and I'm pretty sure I know what the cause is. If i'm right, this will be fixed today

**Closed** 2021-07-12 14:35 UTC
Labels: bug
