### ISSUE TITLE
Exploration Backpacks: Strange behaviour

### ISSUE THREAD

**Issue by mindforger** [MrTJP/ProjectRed#670] opened 2014-12-18 15:31 UTC
When the Backpacks are opened, the inventory behaviour gets glitchy, after several moved items by D&D soemtimes the item gets stuck at the cursor and can only be dropped and not beplaced back into any slot

**Comment by simon816** [comment] 2015-01-08 12:25
Is there a reliable way to reproduce this?

**Comment by MrTJP** [comment] 2015-02-14 17:05
Cant reproduce. Seems fine to me

**Comment by AnrDaemon** [comment] 2015-05-22 17:50
It happens intermittently, but items aren't "stuck", you have to click multiple times to get the item off the cursor. I only encountered it in MP so far.

**Comment by AnrDaemon** [comment] 2015-05-22 21:53
I think I've found somewhat reliable case to reproduce the issue.
Try to pick and place the same item between backpack and inventory. Not shift-click, but exactly pick-put-pick-put.

**Comment by MrTJP** [comment] 2015-05-23 14:33
I will rewrite container code asap.

**Comment by MrTJP** [comment] 2015-05-26 21:06
Fixed via aa190f3d63207e845ebd8ab69b57adddff5cf278

**Closed by MrTJP** 2015-05-26 21:06 UTC
