### ISSUE TITLE
1.10.2 - full backpack still keep crashing the game

### ISSUE THREAD

**Issue by Golummechanic** [MrTJP/ProjectRed#1357] opened 2018-07-11 20:09 UTC
Dear MrTJP,

I have no clue what you mean with _Update_ I have looked around to what you have said to other issue reports of the same time.
I have tried to swap the MrTJPcore from version 20 back to 19 to see if that would get my stuff back what didnt work.
I have even redownloaded version 20 and swaped it out to see if that would work, nothing...

I am at a loss of what to do, its odd you label it as fixed if its clearly not fixed.
If you still have any interest in looking in the problem here are my last crash reports
[crash-2018-07-11_22.01.29-client.txt](https://github.com/MrTJP/ProjectRed/files/2186058/crash-2018-07-11_22.01.29-client.txt)
[crash-2018-07-11_22.03.19-client.txt](https://github.com/MrTJP/ProjectRed/files/2186059/crash-2018-07-11_22.03.19-client.txt)

other data:

Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2488

Project red Mods used:
MrTJPCore-1.10.2-2.0.1.20-universal
ForgeMultipart-1.10.2-2.0.0.38-universal
ProjectRed-1.10.2-4.8.4.49-Base
ProjectRed-1.10.2-4.8.4.49-fabrication
ProjectRed-1.10.2-4.8.4.49-integration
ProjectRed-1.10.2-4.8.4.49-lighting
ProjectRed-1.10.2-4.8.4.49-world

Other mods used:
JustEnoughCalculation-1.10.2-2.6.5
InventoryTweaks-1.62-dev-66
ProjectE-1.10.2-PE1.3.1
Railcraft_1.10.2-10.3.1
RailCraft+Cosmetic+Additions-3.0.5
iChunUtil-1.10.2-6.5.0
PortalGun-1.10.2-6.0.1-fix-1
davincisvessels-1.10.2-0006-full
movingworld-1.10.2-0007-full
IronBackpacks-1.10.2-2.2.33
ironchest-1.10.2-7.0.15.804
GalacticraftCore-1.10.2-4.0.1.181
Galacticraft-Planets-1.10.2-4.0.1.181
MicdoodleCore-1.10.2-4.0.1.181
ModularPowersuits-1.10.2-1.2.129
nuclearphysics-1.10.2-0.1.37
MCMultiPart-1.4.0-universal
Mekanism-1.10.2-9.2.4.103
MekanismGenerators-1.10.2-9.2.4.103
CodeChickenCore-1.10.2-2.4.1.102-universal
jei_1.10.2-3.14.8.422
CodeChickenLib-1.10.2-2.5.9.320-universal
journeymap-1.10.2-5.5.2
NotEnoughItems-1.10.2-2.1.3.220-universal

**Comment by covers1624** [comment] 2018-07-11 20:13
What he means is 1.10 is not supported anymore and the issue is fixed in 1.11.

**Closed by covers1624** 2018-07-11 20:13 UTC
