### ISSUE TITLE
[1.11.2] Project Red "missing mods"

### ISSUE THREAD

**Issue by OmarWazzan** [MrTJP/ProjectRed#1332] opened 2018-06-23 07:44 UTC
![63581d 1](https://user-images.githubusercontent.com/19527321/41807112-3d319e42-76d2-11e8-9ad2-3cd47cf4fbb0.png)

Log file: https://pastebin.com/KWu3Lc3C

both forge and MrTJPCore are installed.

**Comment by MrTJP** [comment] 2018-06-23 15:57
Duplicate of #1300

**Closed by MrTJP** 2018-06-23 15:57 UTC
