### ISSUE TITLE
lags after downloading project red

### ISSUE THREAD

**Issue by BlackHoleTON618** [MrTJP/ProjectRed#1459] opened 2019-02-14 09:40 UTC
i used to get 190 FPS with my old modpack but now i get only 20fps and blocks arent breaking like before i have to break twice and my fps was still 30 20 even render distance is 2 chunks but before even i used 64 chunks i got 60 fps what the hell happened
minecraft 1.12.2
forge 14.2.2768
project red 1.4.38

**Comment by MrTJP** [comment] 2019-07-11 22:09
I need more details. Also that is an invalid version of PojectRed.

**Comment by MrTJP** [comment] 2019-07-18 20:33
Closing because I don't have enough details to reproduce.

**Closed by MrTJP** 2019-07-18 20:33 UTC
Labels: bug
